environment:
  ANDROID_HOME: "C:\\android-sdk-windows"
  ANDROID_NDK_HOME: "C:\\android-sdk-windows\\ndk-bundle"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  ANDROID_TOOLS_URL: "https://dl.google.com/android/repository/tools_r25.2.3-windows.zip"
  MSVC_HOME: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community"

os: Visual Studio 2017

clone_folder: "C:\\projects\\appveyor-android-api-26"
shallow_clone: true

platform:
  # - x86
  - x64

version: '{branch}.{build}'

build:
    verbosity: minimal

init:
  # Download the Android SDK
  - appveyor DownloadFile %ANDROID_TOOLS_URL% -FileName android-tools.zip
  - 7z x android-tools.zip -o"%ANDROID_HOME%" > nul

  # Work around gradle bug https://github.com/gradle/gradle/issues/929
  - set PATH=C:\Program Files (x86)\Windows Kits\8.1\bin\x86;%PATH%

install:
  - mkdir %ANDROID_HOME%\licenses
  - ps: 'Add-Content -Value "`n8933bad161af4178b1185d1a37fbf41ea5269c55`n`nd56f5187479451eabf01fb78af6dfcb131a6481e" -Path $env:ANDROID_HOME\licenses\android-sdk-license -Encoding ASCII'
  - ps: 'Add-Content -Value "`n84831b9409646a918e30573bab4c9c91346d8abd`n504667f4c0de7af1a06de9f4b1727b84351f2910" -Path $env:ANDROID_HOME\licenses\android-sdk-preview-license -Encoding ASCII'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat tools'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat platform-tools'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat build-tools;25.0.0'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat platforms;android-25'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat extras;android;m2repository'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat --channel=1 ndk-bundle'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat cmake;3.6.4111459'